### ISSUE TITLE
"env" should be named "prop"

### ISSUE THREAD

**Issue by ocadaruma** [mogproject/javactl#21]
Currently, configs in `java.env` will be converted to `-D<key>=<value>`.

`-D<key>=<value>`s are called `Java System Property` so I think name like `java.prop` or `java.system_property` is more appropriate.

**Comment by mogproject** [comment]
`-D<key>=<value>`
When the value is a boolean, `true` or `false` should be lowercased.
connected: https://github.com/mogproject/javactl/pull/23

**Comment by mogproject** [comment]
@ocadaruma
Please look over this PR.
https://github.com/mogproject/javactl/pull/24
